name: flutter_architecture
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-97.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.6.4


  fa_presentation:
    path: packages/fa_presentation

  fa_data:
    path: packages/fa_data

  fa_domain:
    path: packages/fa_domain


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.3



flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
